image: alexcheng/ionic:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm i

unit-test:
  script:
    - npm run ci:test

e2e-test:
  script:
    - npm run ci:e2e
